//
// Generated by Bluespec Compiler, version 2022.01-37-gaf852df5 (build af852df5)
//
// On Thu Jun 20 12:37:31 BST 2024
//
//
// Ports:
// Name                         I/O  size props
// wrap64_setValidCapMem          O    65
// wrap64_setValidCapMem_cap      I    65
// wrap64_setValidCapMem_valid    I     1
//
// Combinational paths from inputs to outputs:
//   (wrap64_setValidCapMem_cap,
//    wrap64_setValidCapMem_valid) -> wrap64_setValidCapMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_setValidCapMem(wrap64_setValidCapMem_cap,
				    wrap64_setValidCapMem_valid,
				    wrap64_setValidCapMem);
  // value method wrap64_setValidCapMem
  input  [64 : 0] wrap64_setValidCapMem_cap;
  input  wrap64_setValidCapMem_valid;
  output [64 : 0] wrap64_setValidCapMem;

  // signals for module outputs
  wire [64 : 0] wrap64_setValidCapMem;

  // value method wrap64_setValidCapMem
  assign wrap64_setValidCapMem =
	     { wrap64_setValidCapMem_valid,
	       wrap64_setValidCapMem_cap[63:0] } ;
endmodule  // module_wrap64_setValidCapMem

