//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Mon Oct  4 13:41:46 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getKind                 O     7
// wrap64_getKind_cap             I    91
//
// Combinational paths from inputs to outputs:
//   wrap64_getKind_cap -> wrap64_getKind
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getKind(wrap64_getKind_cap,
			     wrap64_getKind);
  // value method wrap64_getKind
  input  [90 : 0] wrap64_getKind_cap;
  output [6 : 0] wrap64_getKind;

  // signals for module outputs
  reg [6 : 0] wrap64_getKind;

  // value method wrap64_getKind
  always@(wrap64_getKind_cap)
  begin
    case (wrap64_getKind_cap[36:33])
      4'd12: wrap64_getKind = 7'd58;
      4'd13: wrap64_getKind = 7'd42;
      4'd14: wrap64_getKind = 7'd26;
      4'd15: wrap64_getKind = 7'd10;
      default: wrap64_getKind = { 3'd4, wrap64_getKind_cap[36:33] };
    endcase
  end
endmodule  // module_wrap64_getKind

