//
// Generated by Bluespec Compiler (build 6a8cedf)
//
// On Tue Oct 10 19:35:49 UTC 2023
//
//
// Ports:
// Name                         I/O  size props
// wrap64_setTypeCapMem           O    65
// wrap64_setTypeCapMem_capMem    I    65
// wrap64_setTypeCapMem_t         I     4
//
// Combinational paths from inputs to outputs:
//   (wrap64_setTypeCapMem_capMem,
//    wrap64_setTypeCapMem_t) -> wrap64_setTypeCapMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_setTypeCapMem(wrap64_setTypeCapMem_capMem,
				   wrap64_setTypeCapMem_t,
				   wrap64_setTypeCapMem);
  // value method wrap64_setTypeCapMem
  input  [64 : 0] wrap64_setTypeCapMem_capMem;
  input  [3 : 0] wrap64_setTypeCapMem_t;
  output [64 : 0] wrap64_setTypeCapMem;

  // signals for module outputs
  wire [64 : 0] wrap64_setTypeCapMem;

  // value method wrap64_setTypeCapMem
  assign wrap64_setTypeCapMem =
	     { wrap64_setTypeCapMem_capMem[64:51],
	       ~wrap64_setTypeCapMem_t,
	       wrap64_setTypeCapMem_capMem[46:0] } ;
endmodule  // module_wrap64_setTypeCapMem

