//
// Generated by Bluespec Compiler (build 6a8cedf)
//
// On Thu Oct  5 12:21:06 UTC 2023
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getTop                  O    33
// wrap64_getTop_cap              I    91
//
// Combinational paths from inputs to outputs:
//   wrap64_getTop_cap -> wrap64_getTop
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getTop(wrap64_getTop_cap,
			    wrap64_getTop);
  // value method wrap64_getTop
  input  [90 : 0] wrap64_getTop_cap;
  output [32 : 0] wrap64_getTop;

  // signals for module outputs
  wire [32 : 0] wrap64_getTop;

  // remaining internal signals
  wire [32 : 0] addTop__h62, result__h506, ret__h64;
  wire [24 : 0] mask__h63;
  wire [23 : 0] wrap64_getTop_cap_BITS_89_TO_66_PLUS_SEXT_wrap_ETC__q2;
  wire [9 : 0] x__h172;
  wire [1 : 0] wrap64_getTop_cap_BITS_1_TO_0__q1;

  // value method wrap64_getTop
  assign wrap64_getTop =
	     (wrap64_getTop_cap[31:26] < 6'd25 &&
	      ret__h64[32:31] -
	      { 1'b0,
		(wrap64_getTop_cap[31:26] == 6'd24) ?
		  wrap64_getTop_cap[17] :
		  wrap64_getTop_cap_BITS_89_TO_66_PLUS_SEXT_wrap_ETC__q2[23] } >
	      2'd1) ?
	       result__h506 :
	       ret__h64 ;

  // remaining internal signals
  assign addTop__h62 =
	     { {23{x__h172[9]}}, x__h172 } << wrap64_getTop_cap[31:26] ;
  assign mask__h63 = 25'd33554431 << wrap64_getTop_cap[31:26] ;
  assign result__h506 = { ~ret__h64[32], ret__h64[31:0] } ;
  assign ret__h64 =
	     { { 1'b0, wrap64_getTop_cap[89:66] } & mask__h63, 8'd0 } +
	     addTop__h62 ;
  assign wrap64_getTop_cap_BITS_1_TO_0__q1 = wrap64_getTop_cap[1:0] ;
  assign wrap64_getTop_cap_BITS_89_TO_66_PLUS_SEXT_wrap_ETC__q2 =
	     wrap64_getTop_cap[89:66] +
	     ({ {22{wrap64_getTop_cap_BITS_1_TO_0__q1[1]}},
		wrap64_getTop_cap_BITS_1_TO_0__q1 } <<
	      wrap64_getTop_cap[31:26]) ;
  assign x__h172 = { wrap64_getTop_cap[3:2], wrap64_getTop_cap[25:18] } ;
endmodule  // module_wrap64_getTop

