//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Mon Sep 20 15:37:53 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_modifyOffset            O    92
// wrap64_modifyOffset_cap        I    91
// wrap64_modifyOffset_offset     I    32
// wrap64_modifyOffset_doInc      I     1
//
// Combinational paths from inputs to outputs:
//   (wrap64_modifyOffset_cap,
//    wrap64_modifyOffset_offset,
//    wrap64_modifyOffset_doInc) -> wrap64_modifyOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_modifyOffset(wrap64_modifyOffset_cap,
				  wrap64_modifyOffset_offset,
				  wrap64_modifyOffset_doInc,
				  wrap64_modifyOffset);
  // value method wrap64_modifyOffset
  input  [90 : 0] wrap64_modifyOffset_cap;
  input  [31 : 0] wrap64_modifyOffset_offset;
  input  wrap64_modifyOffset_doInc;
  output [91 : 0] wrap64_modifyOffset;

  // signals for module outputs
  wire [91 : 0] wrap64_modifyOffset;

  // remaining internal signals
  reg [1 : 0] mask__h574;
  wire [31 : 0] addBase__h616,
		pointer__h67,
		result_d_address__h588,
		ret___1_address__h598,
		x__h480,
		x__h726;
  wire [23 : 0] highOffsetBits__h74, mask__h617, signBits__h71, x__h101;
  wire [9 : 0] x__h667;
  wire [7 : 0] newAddrBits__h573,
	       repBoundBits__h80,
	       result_d_addrBits__h589,
	       toBoundsM1_A__h79,
	       toBoundsM1_B__h82,
	       toBoundsM1__h84,
	       toBounds_A__h78,
	       toBounds_B__h81,
	       toBounds__h83;
  wire [3 : 0] IF_wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_ETC___d83;
  wire [2 : 0] repBound__h865;
  wire IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73,
       IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34,
       NOT_wrap64_modifyOffset_offset_SRL_wrap64_modi_ETC___d25,
       wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71,
       wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70;

  // value method wrap64_modifyOffset
  assign wrap64_modifyOffset =
	     { highOffsetBits__h74 == 24'd0 &&
	       IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34 ||
	       wrap64_modifyOffset_cap[31:26] >= 6'd24,
	       (highOffsetBits__h74 == 24'd0 &&
		IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34 ||
		wrap64_modifyOffset_cap[31:26] >= 6'd24) &&
	       wrap64_modifyOffset_cap[90],
	       result_d_address__h588,
	       result_d_addrBits__h589,
	       wrap64_modifyOffset_cap[49:10],
	       repBound__h865,
	       wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70,
	       wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71,
	       IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73,
	       IF_wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_ETC___d83 } ;

  // remaining internal signals
  assign IF_wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_ETC___d83 =
	     { (wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70 ==
		IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		 2'd0 :
		 ((wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70 &&
		   !IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		    2'd1 :
		    2'd3),
	       (wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71 ==
		IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		 2'd0 :
		 ((wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71 &&
		   !IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73 =
	     result_d_addrBits__h589[7:5] < repBound__h865 ;
  assign IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34 =
	     wrap64_modifyOffset_offset[31] ?
	       NOT_wrap64_modifyOffset_offset_SRL_wrap64_modi_ETC___d25 :
	       (wrap64_modifyOffset_doInc ?
		  x__h480[7:0] < toBoundsM1__h84 :
		  x__h480[7:0] <= toBoundsM1__h84) ;
  assign NOT_wrap64_modifyOffset_offset_SRL_wrap64_modi_ETC___d25 =
	     x__h480[7:0] >= toBounds__h83 &&
	     (!wrap64_modifyOffset_doInc ||
	      repBoundBits__h80 != wrap64_modifyOffset_cap[57:50]) ;
  assign addBase__h616 =
	     { {22{x__h667[9]}}, x__h667 } << wrap64_modifyOffset_cap[31:26] ;
  assign highOffsetBits__h74 = x__h101 & mask__h617 ;
  assign mask__h617 = 24'd16777215 << wrap64_modifyOffset_cap[31:26] ;
  assign newAddrBits__h573 = wrap64_modifyOffset_cap[17:10] + x__h480[7:0] ;
  assign pointer__h67 =
	     wrap64_modifyOffset_cap[89:58] + wrap64_modifyOffset_offset ;
  assign repBoundBits__h80 = { wrap64_modifyOffset_cap[9:7], 5'd0 } ;
  assign repBound__h865 = wrap64_modifyOffset_cap[17:15] - 3'b001 ;
  assign result_d_addrBits__h589 =
	     wrap64_modifyOffset_doInc ?
	       x__h726[7:0] :
	       { mask__h574, 6'd63 } & newAddrBits__h573 ;
  assign result_d_address__h588 =
	     wrap64_modifyOffset_doInc ?
	       pointer__h67 :
	       ret___1_address__h598 ;
  assign ret___1_address__h598 =
	     { wrap64_modifyOffset_cap[89:66] & mask__h617, 8'd0 } +
	     addBase__h616 +
	     wrap64_modifyOffset_offset ;
  assign signBits__h71 = {24{wrap64_modifyOffset_offset[31]}} ;
  assign toBoundsM1_A__h79 = { 3'b110, ~wrap64_modifyOffset_cap[14:10] } ;
  assign toBoundsM1_B__h82 =
	     repBoundBits__h80 + ~wrap64_modifyOffset_cap[57:50] ;
  assign toBoundsM1__h84 =
	     wrap64_modifyOffset_doInc ?
	       toBoundsM1_B__h82 :
	       toBoundsM1_A__h79 ;
  assign toBounds_A__h78 = 8'd224 - { 3'b0, wrap64_modifyOffset_cap[14:10] } ;
  assign toBounds_B__h81 =
	     repBoundBits__h80 - wrap64_modifyOffset_cap[57:50] ;
  assign toBounds__h83 =
	     wrap64_modifyOffset_doInc ? toBounds_B__h81 : toBounds_A__h78 ;
  assign wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71 =
	     wrap64_modifyOffset_cap[17:15] < repBound__h865 ;
  assign wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70 =
	     wrap64_modifyOffset_cap[25:23] < repBound__h865 ;
  assign x__h101 = wrap64_modifyOffset_offset[31:8] ^ signBits__h71 ;
  assign x__h480 =
	     wrap64_modifyOffset_offset >> wrap64_modifyOffset_cap[31:26] ;
  assign x__h667 =
	     { wrap64_modifyOffset_cap[1:0],
	       wrap64_modifyOffset_cap[17:10] } ;
  assign x__h726 = pointer__h67 >> wrap64_modifyOffset_cap[31:26] ;
  always@(wrap64_modifyOffset_cap)
  begin
    case (wrap64_modifyOffset_cap[31:26])
      6'd25: mask__h574 = 2'b01;
      6'd26: mask__h574 = 2'b0;
      default: mask__h574 = 2'b11;
    endcase
  end
endmodule  // module_wrap64_modifyOffset

