//
// Generated by Bluespec Compiler, version 2022.01-37-gaf852df5 (build af852df5)
//
// On Thu Jun 20 12:37:31 BST 2024
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getTypeCapMem           O     4
// wrap64_getTypeCapMem_capMem    I    65
//
// Combinational paths from inputs to outputs:
//   wrap64_getTypeCapMem_capMem -> wrap64_getTypeCapMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getTypeCapMem(wrap64_getTypeCapMem_capMem,
				   wrap64_getTypeCapMem);
  // value method wrap64_getTypeCapMem
  input  [64 : 0] wrap64_getTypeCapMem_capMem;
  output [3 : 0] wrap64_getTypeCapMem;

  // signals for module outputs
  wire [3 : 0] wrap64_getTypeCapMem;

  // value method wrap64_getTypeCapMem
  assign wrap64_getTypeCapMem = ~wrap64_getTypeCapMem_capMem[50:47] ;
endmodule  // module_wrap64_getTypeCapMem

