//
// Generated by Bluespec Compiler, version 2022.01-37-gaf852df5 (build af852df5)
//
// On Thu Jun 20 12:37:29 BST 2024
//
//
// Ports:
// Name                         I/O  size props
// wrap64_setType                 O    91
// wrap64_setType_cap             I    91
// wrap64_setType_t               I     4
//
// Combinational paths from inputs to outputs:
//   (wrap64_setType_cap, wrap64_setType_t) -> wrap64_setType
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_setType(wrap64_setType_cap,
			     wrap64_setType_t,
			     wrap64_setType);
  // value method wrap64_setType
  input  [90 : 0] wrap64_setType_cap;
  input  [3 : 0] wrap64_setType_t;
  output [90 : 0] wrap64_setType;

  // signals for module outputs
  wire [90 : 0] wrap64_setType;

  // remaining internal signals
  reg [3 : 0] CASE_wrap64_setType_t_12_wrap64_setType_t_13_w_ETC__q1;

  // value method wrap64_setType
  assign wrap64_setType =
	     { wrap64_setType_cap[90:37],
	       CASE_wrap64_setType_t_12_wrap64_setType_t_13_w_ETC__q1,
	       wrap64_setType_cap[32:0] } ;

  // remaining internal signals
  always@(wrap64_setType_t)
  begin
    case (wrap64_setType_t)
      4'd12, 4'd13, 4'd14, 4'd15:
	  CASE_wrap64_setType_t_12_wrap64_setType_t_13_w_ETC__q1 =
	      wrap64_setType_t;
      default: CASE_wrap64_setType_t_12_wrap64_setType_t_13_w_ETC__q1 =
		   wrap64_setType_t;
    endcase
  end
endmodule  // module_wrap64_setType

