//
// Generated by Bluespec Compiler (build 6a8cedf)
//
// On Thu Oct  5 12:21:07 UTC 2023
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getPermsCapMem          O    31
// wrap64_getPermsCapMem_capMem   I    65
//
// Combinational paths from inputs to outputs:
//   wrap64_getPermsCapMem_capMem -> wrap64_getPermsCapMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getPermsCapMem(wrap64_getPermsCapMem_capMem,
				    wrap64_getPermsCapMem);
  // value method wrap64_getPermsCapMem
  input  [64 : 0] wrap64_getPermsCapMem_capMem;
  output [30 : 0] wrap64_getPermsCapMem;

  // signals for module outputs
  wire [30 : 0] wrap64_getPermsCapMem;

  // value method wrap64_getPermsCapMem
  assign wrap64_getPermsCapMem =
	     { 19'd0, wrap64_getPermsCapMem_capMem[63:52] } ;
endmodule  // module_wrap64_getPermsCapMem

