//
// Generated by Bluespec Compiler (build 6a8cedf)
//
// On Tue Oct 10 19:35:47 UTC 2023
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getFlags                O     1
// wrap64_getFlags_cap            I    91
//
// Combinational paths from inputs to outputs:
//   wrap64_getFlags_cap -> wrap64_getFlags
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getFlags(wrap64_getFlags_cap,
			      wrap64_getFlags);
  // value method wrap64_getFlags
  input  [90 : 0] wrap64_getFlags_cap;
  output wrap64_getFlags;

  // signals for module outputs
  wire wrap64_getFlags;

  // value method wrap64_getFlags
  assign wrap64_getFlags = wrap64_getFlags_cap[37] ;
endmodule  // module_wrap64_getFlags

