//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Tue Aug 10 09:31:29 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_isInBounds              O     1
// wrap64_isInBounds_cap          I    91
// wrap64_isInBounds_isTopIncluded  I     1
//
// Combinational paths from inputs to outputs:
//   (wrap64_isInBounds_cap,
//    wrap64_isInBounds_isTopIncluded) -> wrap64_isInBounds
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_isInBounds(wrap64_isInBounds_cap,
				wrap64_isInBounds_isTopIncluded,
				wrap64_isInBounds);
  // value method wrap64_isInBounds
  input  [90 : 0] wrap64_isInBounds_cap;
  input  wrap64_isInBounds_isTopIncluded;
  output wrap64_isInBounds;

  // signals for module outputs
  wire wrap64_isInBounds;

  // value method wrap64_isInBounds
  assign wrap64_isInBounds =
	     ((wrap64_isInBounds_cap[6] == wrap64_isInBounds_cap[4]) ?
		(wrap64_isInBounds_isTopIncluded ?
		   wrap64_isInBounds_cap[57:50] <=
		   wrap64_isInBounds_cap[25:18] :
		   wrap64_isInBounds_cap[57:50] <
		   wrap64_isInBounds_cap[25:18]) :
		wrap64_isInBounds_cap[6]) &&
	     ((wrap64_isInBounds_cap[5] == wrap64_isInBounds_cap[4]) ?
		wrap64_isInBounds_cap[57:50] >= wrap64_isInBounds_cap[17:10] :
		wrap64_isInBounds_cap[4]) ;
endmodule  // module_wrap64_isInBounds

