//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Sat Sep 25 09:11:04 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getOffset               O    32
// wrap64_getOffset_cap           I    91
//
// Combinational paths from inputs to outputs:
//   wrap64_getOffset_cap -> wrap64_getOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getOffset(wrap64_getOffset_cap,
			       wrap64_getOffset);
  // value method wrap64_getOffset
  input  [90 : 0] wrap64_getOffset_cap;
  output [31 : 0] wrap64_getOffset;

  // signals for module outputs
  wire [31 : 0] wrap64_getOffset;

  // remaining internal signals
  wire [31 : 0] addrLSB__h61, x__h193, x__h72, x__h74, y__h192;
  wire [9 : 0] base__h59, offset__h60;

  // value method wrap64_getOffset
  assign wrap64_getOffset = x__h72 | addrLSB__h61 ;

  // remaining internal signals
  assign addrLSB__h61 = wrap64_getOffset_cap[89:58] & y__h192 ;
  assign base__h59 =
	     { wrap64_getOffset_cap[1:0], wrap64_getOffset_cap[17:10] } ;
  assign offset__h60 = { 2'b0, wrap64_getOffset_cap[57:50] } - base__h59 ;
  assign x__h193 = 32'hFFFFFFFF << wrap64_getOffset_cap[31:26] ;
  assign x__h72 = x__h74 << wrap64_getOffset_cap[31:26] ;
  assign x__h74 = { {22{offset__h60[9]}}, offset__h60 } ;
  assign y__h192 = ~x__h193 ;
endmodule  // module_wrap64_getOffset

