//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Tue Aug 10 09:31:29 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_modifyOffset            O    92
// wrap64_modifyOffset_cap        I    91
// wrap64_modifyOffset_offset     I    32
// wrap64_modifyOffset_doInc      I     1
//
// Combinational paths from inputs to outputs:
//   (wrap64_modifyOffset_cap,
//    wrap64_modifyOffset_offset,
//    wrap64_modifyOffset_doInc) -> wrap64_modifyOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_modifyOffset(wrap64_modifyOffset_cap,
				  wrap64_modifyOffset_offset,
				  wrap64_modifyOffset_doInc,
				  wrap64_modifyOffset);
  // value method wrap64_modifyOffset
  input  [90 : 0] wrap64_modifyOffset_cap;
  input  [31 : 0] wrap64_modifyOffset_offset;
  input  wrap64_modifyOffset_doInc;
  output [91 : 0] wrap64_modifyOffset;

  // signals for module outputs
  wire [91 : 0] wrap64_modifyOffset;

  // remaining internal signals
  reg [1 : 0] mask__h573;
  wire [31 : 0] addBase__h615,
		pointer__h66,
		result_d_address__h587,
		ret___1_address__h597,
		x__h479,
		x__h725;
  wire [23 : 0] highOffsetBits__h73, mask__h616, signBits__h70, x__h100;
  wire [9 : 0] x__h666;
  wire [7 : 0] newAddrBits__h572,
	       repBoundBits__h79,
	       result_d_addrBits__h588,
	       toBoundsM1_A__h78,
	       toBoundsM1_B__h81,
	       toBoundsM1__h83,
	       toBounds_A__h77,
	       toBounds_B__h80,
	       toBounds__h82;
  wire [3 : 0] IF_wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_ETC___d83;
  wire [2 : 0] repBound__h864;
  wire IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73,
       IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34,
       NOT_wrap64_modifyOffset_offset_SRL_wrap64_modi_ETC___d25,
       wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71,
       wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70;

  // value method wrap64_modifyOffset
  assign wrap64_modifyOffset =
	     { highOffsetBits__h73 == 24'd0 &&
	       IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34 ||
	       wrap64_modifyOffset_cap[31:26] >= 6'd24,
	       (highOffsetBits__h73 == 24'd0 &&
		IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34 ||
		wrap64_modifyOffset_cap[31:26] >= 6'd24) &&
	       wrap64_modifyOffset_cap[90],
	       result_d_address__h587,
	       result_d_addrBits__h588,
	       wrap64_modifyOffset_cap[49:10],
	       repBound__h864,
	       wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70,
	       wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71,
	       IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73,
	       IF_wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_ETC___d83 } ;

  // remaining internal signals
  assign IF_wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_ETC___d83 =
	     { (wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70 ==
		IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		 2'd0 :
		 ((wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70 &&
		   !IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		    2'd1 :
		    2'd3),
	       (wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71 ==
		IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		 2'd0 :
		 ((wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71 &&
		   !IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_wrap64_modifyOffset_doInc_THEN_wrap64_modif_ETC___d73 =
	     result_d_addrBits__h588[7:5] < repBound__h864 ;
  assign IF_wrap64_modifyOffset_offset_BIT_31_THEN_NOT__ETC___d34 =
	     wrap64_modifyOffset_offset[31] ?
	       NOT_wrap64_modifyOffset_offset_SRL_wrap64_modi_ETC___d25 :
	       (wrap64_modifyOffset_doInc ?
		  x__h479[7:0] < toBoundsM1__h83 :
		  x__h479[7:0] <= toBoundsM1__h83) ;
  assign NOT_wrap64_modifyOffset_offset_SRL_wrap64_modi_ETC___d25 =
	     x__h479[7:0] >= toBounds__h82 &&
	     (!wrap64_modifyOffset_doInc ||
	      repBoundBits__h79 != wrap64_modifyOffset_cap[57:50]) ;
  assign addBase__h615 =
	     { {22{x__h666[9]}}, x__h666 } << wrap64_modifyOffset_cap[31:26] ;
  assign highOffsetBits__h73 = x__h100 & mask__h616 ;
  assign mask__h616 = 24'd16777215 << wrap64_modifyOffset_cap[31:26] ;
  assign newAddrBits__h572 = wrap64_modifyOffset_cap[17:10] + x__h479[7:0] ;
  assign pointer__h66 =
	     wrap64_modifyOffset_cap[89:58] + wrap64_modifyOffset_offset ;
  assign repBoundBits__h79 = { wrap64_modifyOffset_cap[9:7], 5'd0 } ;
  assign repBound__h864 = wrap64_modifyOffset_cap[17:15] - 3'b001 ;
  assign result_d_addrBits__h588 =
	     wrap64_modifyOffset_doInc ?
	       x__h725[7:0] :
	       { mask__h573, 6'd63 } & newAddrBits__h572 ;
  assign result_d_address__h587 =
	     wrap64_modifyOffset_doInc ?
	       pointer__h66 :
	       ret___1_address__h597 ;
  assign ret___1_address__h597 =
	     { wrap64_modifyOffset_cap[89:66] & mask__h616, 8'd0 } +
	     addBase__h615 +
	     wrap64_modifyOffset_offset ;
  assign signBits__h70 = {24{wrap64_modifyOffset_offset[31]}} ;
  assign toBoundsM1_A__h78 = { 3'b110, ~wrap64_modifyOffset_cap[14:10] } ;
  assign toBoundsM1_B__h81 =
	     repBoundBits__h79 + ~wrap64_modifyOffset_cap[57:50] ;
  assign toBoundsM1__h83 =
	     wrap64_modifyOffset_doInc ?
	       toBoundsM1_B__h81 :
	       toBoundsM1_A__h78 ;
  assign toBounds_A__h77 = 8'd224 - { 3'b0, wrap64_modifyOffset_cap[14:10] } ;
  assign toBounds_B__h80 =
	     repBoundBits__h79 - wrap64_modifyOffset_cap[57:50] ;
  assign toBounds__h82 =
	     wrap64_modifyOffset_doInc ? toBounds_B__h80 : toBounds_A__h77 ;
  assign wrap64_modifyOffset_cap_BITS_17_TO_15_7_ULT_wr_ETC___d71 =
	     wrap64_modifyOffset_cap[17:15] < repBound__h864 ;
  assign wrap64_modifyOffset_cap_BITS_25_TO_23_9_ULT_wr_ETC___d70 =
	     wrap64_modifyOffset_cap[25:23] < repBound__h864 ;
  assign x__h100 = wrap64_modifyOffset_offset[31:8] ^ signBits__h70 ;
  assign x__h479 =
	     wrap64_modifyOffset_offset >> wrap64_modifyOffset_cap[31:26] ;
  assign x__h666 =
	     { wrap64_modifyOffset_cap[1:0],
	       wrap64_modifyOffset_cap[17:10] } ;
  assign x__h725 = pointer__h66 >> wrap64_modifyOffset_cap[31:26] ;
  always@(wrap64_modifyOffset_cap)
  begin
    case (wrap64_modifyOffset_cap[31:26])
      6'd25: mask__h573 = 2'b01;
      6'd26: mask__h573 = 2'b0;
      default: mask__h573 = 2'b11;
    endcase
  end
endmodule  // module_wrap64_modifyOffset

