//
// Generated by Bluespec Compiler, version 2022.01-37-gaf852df5 (build af852df5)
//
// On Fri Jul  5 14:25:24 BST 2024
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getHardPermsCapMem      O    12
// wrap64_getHardPermsCapMem_cap  I    65
//
// Combinational paths from inputs to outputs:
//   wrap64_getHardPermsCapMem_cap -> wrap64_getHardPermsCapMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getHardPermsCapMem(wrap64_getHardPermsCapMem_cap,
					wrap64_getHardPermsCapMem);
  // value method wrap64_getHardPermsCapMem
  input  [64 : 0] wrap64_getHardPermsCapMem_cap;
  output [11 : 0] wrap64_getHardPermsCapMem;

  // signals for module outputs
  wire [11 : 0] wrap64_getHardPermsCapMem;

  // value method wrap64_getHardPermsCapMem
  assign wrap64_getHardPermsCapMem = wrap64_getHardPermsCapMem_cap[63:52] ;
endmodule  // module_wrap64_getHardPermsCapMem

