//
// Generated by Bluespec Compiler, version 2022.01-37-gaf852df5 (build af852df5)
//
// On Thu Jun 20 12:37:30 BST 2024
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getMeta                 O    32
// wrap64_getMeta_cap             I    91
//
// Combinational paths from inputs to outputs:
//   wrap64_getMeta_cap -> wrap64_getMeta
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getMeta(wrap64_getMeta_cap,
			     wrap64_getMeta);
  // value method wrap64_getMeta
  input  [90 : 0] wrap64_getMeta_cap;
  output [31 : 0] wrap64_getMeta;

  // signals for module outputs
  wire [31 : 0] wrap64_getMeta;

  // remaining internal signals
  wire [14 : 0] cap_bounds__h165;
  wire [13 : 0] IF_wrap64_getMeta_cap_BIT_32_THEN_wrap64_getMe_ETC___d14;
  wire [4 : 0] INV_wrap64_getMeta_cap_BITS_36_TO_32__q1;

  // value method wrap64_getMeta
  assign wrap64_getMeta =
	     { wrap64_getMeta_cap[49:37],
	       INV_wrap64_getMeta_cap_BITS_36_TO_32__q1[4:1],
	       cap_bounds__h165 } ;

  // remaining internal signals
  assign IF_wrap64_getMeta_cap_BIT_32_THEN_wrap64_getMe_ETC___d14 =
	     wrap64_getMeta_cap[32] ?
	       { wrap64_getMeta_cap[23:21],
		 wrap64_getMeta_cap[31:29],
		 wrap64_getMeta_cap[17:13],
		 wrap64_getMeta_cap[28:26] } :
	       wrap64_getMeta_cap[23:10] ;
  assign INV_wrap64_getMeta_cap_BITS_36_TO_32__q1 =
	     ~wrap64_getMeta_cap[36:32] ;
  assign cap_bounds__h165 =
	     { INV_wrap64_getMeta_cap_BITS_36_TO_32__q1[0],
	       IF_wrap64_getMeta_cap_BIT_32_THEN_wrap64_getMe_ETC___d14[13:10],
	       ~IF_wrap64_getMeta_cap_BIT_32_THEN_wrap64_getMe_ETC___d14[9:8],
	       IF_wrap64_getMeta_cap_BIT_32_THEN_wrap64_getMe_ETC___d14[7:2],
	       ~IF_wrap64_getMeta_cap_BIT_32_THEN_wrap64_getMe_ETC___d14[1],
	       IF_wrap64_getMeta_cap_BIT_32_THEN_wrap64_getMe_ETC___d14[0] } ;
endmodule  // module_wrap64_getMeta

