//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Tue Aug 10 09:31:29 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getOffset               O    32
// wrap64_getOffset_cap           I    91
//
// Combinational paths from inputs to outputs:
//   wrap64_getOffset_cap -> wrap64_getOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getOffset(wrap64_getOffset_cap,
			       wrap64_getOffset);
  // value method wrap64_getOffset
  input  [90 : 0] wrap64_getOffset_cap;
  output [31 : 0] wrap64_getOffset;

  // signals for module outputs
  wire [31 : 0] wrap64_getOffset;

  // remaining internal signals
  wire [31 : 0] addrLSB__h60, x__h192, x__h71, x__h73, y__h191;
  wire [9 : 0] base__h58, offset__h59;

  // value method wrap64_getOffset
  assign wrap64_getOffset = x__h71 | addrLSB__h60 ;

  // remaining internal signals
  assign addrLSB__h60 = wrap64_getOffset_cap[89:58] & y__h191 ;
  assign base__h58 =
	     { wrap64_getOffset_cap[1:0], wrap64_getOffset_cap[17:10] } ;
  assign offset__h59 = { 2'b0, wrap64_getOffset_cap[57:50] } - base__h58 ;
  assign x__h192 = 32'hFFFFFFFF << wrap64_getOffset_cap[31:26] ;
  assign x__h71 = x__h73 << wrap64_getOffset_cap[31:26] ;
  assign x__h73 = { {22{offset__h59[9]}}, offset__h59 } ;
  assign y__h191 = ~x__h192 ;
endmodule  // module_wrap64_getOffset

