//
// Generated by Bluespec Compiler (build 6a8cedf)
//
// On Tue Oct 10 19:35:48 UTC 2023
//
//
// Ports:
// Name                         I/O  size props
// wrap64_nullCapPipe             O    91 const
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_nullCapPipe(wrap64_nullCapPipe);
  // value method wrap64_nullCapPipe
  output [90 : 0] wrap64_nullCapPipe;

  // signals for module outputs
  wire [90 : 0] wrap64_nullCapPipe;

  // value method wrap64_nullCapPipe
  assign wrap64_nullCapPipe = 91'h00000000000001F690003F0 ;
endmodule  // module_wrap64_nullCapPipe

