//
// Generated by Bluespec Compiler (build 6a8cedf)
//
// On Tue Oct 10 19:35:51 UTC 2023
//
//
// Ports:
// Name                         I/O  size props
// wrap64_vectorBoundsDecompress  O  2080
// wrap64_vectorBoundsDecompress_cboundsRaw  I    15
// wrap64_vectorBoundsDecompress_addrs  I  1024
//
// Combinational paths from inputs to outputs:
//   (wrap64_vectorBoundsDecompress_cboundsRaw,
//    wrap64_vectorBoundsDecompress_addrs) -> wrap64_vectorBoundsDecompress
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_vectorBoundsDecompress(wrap64_vectorBoundsDecompress_cboundsRaw,
					    wrap64_vectorBoundsDecompress_addrs,
					    wrap64_vectorBoundsDecompress);
  // value method wrap64_vectorBoundsDecompress
  input  [14 : 0] wrap64_vectorBoundsDecompress_cboundsRaw;
  input  [1023 : 0] wrap64_vectorBoundsDecompress_addrs;
  output [2079 : 0] wrap64_vectorBoundsDecompress;

  // signals for module outputs
  wire [2079 : 0] wrap64_vectorBoundsDecompress;

  // remaining internal signals
  wire [32 : 0] baseBitsFull__h1297,
		result__h11443,
		result__h13486,
		result__h15529,
		result__h17572,
		result__h19615,
		result__h21658,
		result__h23701,
		result__h25744,
		result__h27787,
		result__h29830,
		result__h31873,
		result__h33916,
		result__h35959,
		result__h38002,
		result__h40045,
		result__h42088,
		result__h44131,
		result__h46174,
		result__h48217,
		result__h50260,
		result__h52303,
		result__h54346,
		result__h56389,
		result__h58432,
		result__h60475,
		result__h62518,
		result__h64561,
		result__h66604,
		result__h68647,
		result__h70690,
		result__h7357,
		result__h9400,
		topBitsFull__h1298,
		top__h1509,
		top__h1524,
		top__h1539,
		top__h1554,
		top__h1569,
		top__h1584,
		top__h1599,
		top__h1614,
		top__h1629,
		top__h1644,
		top__h1659,
		top__h1674,
		top__h1689,
		top__h1704,
		top__h1719,
		top__h1734,
		top__h1749,
		top__h1764,
		top__h1779,
		top__h1794,
		top__h1809,
		top__h1824,
		top__h1839,
		top__h1854,
		top__h1869,
		top__h1884,
		top__h1899,
		top__h1914,
		top__h1929,
		top__h1944,
		top__h1959,
		top__h1974,
		x__h11153,
		x__h11543,
		x__h13196,
		x__h13586,
		x__h15239,
		x__h15629,
		x__h17282,
		x__h17672,
		x__h19325,
		x__h19715,
		x__h21368,
		x__h21758,
		x__h23411,
		x__h23801,
		x__h25454,
		x__h25844,
		x__h27497,
		x__h27887,
		x__h29540,
		x__h2967,
		x__h29930,
		x__h31583,
		x__h31973,
		x__h33626,
		x__h34016,
		x__h35669,
		x__h36059,
		x__h37712,
		x__h38102,
		x__h39755,
		x__h40145,
		x__h41798,
		x__h42188,
		x__h43841,
		x__h44231,
		x__h45884,
		x__h46274,
		x__h47927,
		x__h48317,
		x__h49970,
		x__h50360,
		x__h52013,
		x__h52403,
		x__h54056,
		x__h54446,
		x__h56099,
		x__h56489,
		x__h58142,
		x__h58532,
		x__h60185,
		x__h60575,
		x__h62228,
		x__h62618,
		x__h64271,
		x__h64661,
		x__h66314,
		x__h66704,
		x__h68357,
		x__h68747,
		x__h6979,
		x__h70400,
		x__h7457,
		x__h9110,
		x__h9500;
  wire [31 : 0] x__h11107,
		x__h13150,
		x__h15193,
		x__h17236,
		x__h19279,
		x__h21322,
		x__h23365,
		x__h25408,
		x__h27451,
		x__h29494,
		x__h31537,
		x__h33580,
		x__h35623,
		x__h37666,
		x__h39709,
		x__h41752,
		x__h43795,
		x__h45838,
		x__h47881,
		x__h49924,
		x__h51967,
		x__h54010,
		x__h56053,
		x__h58096,
		x__h60139,
		x__h62182,
		x__h64225,
		x__h66268,
		x__h68311,
		x__h6863,
		x__h70354,
		x__h9064;
  wire [24 : 0] addrUpperBits__h1504,
		addrUpperBits__h1519,
		addrUpperBits__h1534,
		addrUpperBits__h1549,
		addrUpperBits__h1564,
		addrUpperBits__h1579,
		addrUpperBits__h1594,
		addrUpperBits__h1609,
		addrUpperBits__h1624,
		addrUpperBits__h1639,
		addrUpperBits__h1654,
		addrUpperBits__h1669,
		addrUpperBits__h1684,
		addrUpperBits__h1699,
		addrUpperBits__h1714,
		addrUpperBits__h1729,
		addrUpperBits__h1744,
		addrUpperBits__h1759,
		addrUpperBits__h1774,
		addrUpperBits__h1789,
		addrUpperBits__h1804,
		addrUpperBits__h1819,
		addrUpperBits__h1834,
		addrUpperBits__h1849,
		addrUpperBits__h1864,
		addrUpperBits__h1879,
		addrUpperBits__h1894,
		addrUpperBits__h1909,
		addrUpperBits__h1924,
		addrUpperBits__h1939,
		addrUpperBits__h1954,
		addrUpperBits__h1969,
		addrUpperHi__h1505,
		addrUpperHi__h1520,
		addrUpperHi__h1535,
		addrUpperHi__h1550,
		addrUpperHi__h1565,
		addrUpperHi__h1580,
		addrUpperHi__h1595,
		addrUpperHi__h1610,
		addrUpperHi__h1625,
		addrUpperHi__h1640,
		addrUpperHi__h1655,
		addrUpperHi__h1670,
		addrUpperHi__h1685,
		addrUpperHi__h1700,
		addrUpperHi__h1715,
		addrUpperHi__h1730,
		addrUpperHi__h1745,
		addrUpperHi__h1760,
		addrUpperHi__h1775,
		addrUpperHi__h1790,
		addrUpperHi__h1805,
		addrUpperHi__h1820,
		addrUpperHi__h1835,
		addrUpperHi__h1850,
		addrUpperHi__h1865,
		addrUpperHi__h1880,
		addrUpperHi__h1895,
		addrUpperHi__h1910,
		addrUpperHi__h1925,
		addrUpperHi__h1940,
		addrUpperHi__h1955,
		addrUpperHi__h1970,
		addrUpperLo__h1506,
		addrUpperLo__h1521,
		addrUpperLo__h1536,
		addrUpperLo__h1551,
		addrUpperLo__h1566,
		addrUpperLo__h1581,
		addrUpperLo__h1596,
		addrUpperLo__h1611,
		addrUpperLo__h1626,
		addrUpperLo__h1641,
		addrUpperLo__h1656,
		addrUpperLo__h1671,
		addrUpperLo__h1686,
		addrUpperLo__h1701,
		addrUpperLo__h1716,
		addrUpperLo__h1731,
		addrUpperLo__h1746,
		addrUpperLo__h1761,
		addrUpperLo__h1776,
		addrUpperLo__h1791,
		addrUpperLo__h1806,
		addrUpperLo__h1821,
		addrUpperLo__h1836,
		addrUpperLo__h1851,
		addrUpperLo__h1866,
		addrUpperLo__h1881,
		addrUpperLo__h1896,
		addrUpperLo__h1911,
		addrUpperLo__h1926,
		addrUpperLo__h1941,
		addrUpperLo__h1956,
		addrUpperLo__h1971,
		allOnesExpShifted__h1301,
		oneExpShifted__h1302;
  wire [7 : 0] b_base__h4648,
	       topBits__h1295,
	       x__h10352,
	       x__h12395,
	       x__h14438,
	       x__h16481,
	       x__h18524,
	       x__h20567,
	       x__h22610,
	       x__h24653,
	       x__h26696,
	       x__h28739,
	       x__h30782,
	       x__h32825,
	       x__h34868,
	       x__h36911,
	       x__h38954,
	       x__h40997,
	       x__h43040,
	       x__h45083,
	       x__h47126,
	       x__h49169,
	       x__h51212,
	       x__h53255,
	       x__h5438,
	       x__h55298,
	       x__h57341,
	       x__h59384,
	       x__h61427,
	       x__h63470,
	       x__h65513,
	       x__h67556,
	       x__h69599,
	       x__h7008,
	       x__h8309;
  wire [5 : 0] IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23,
	       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d50,
	       b_top__h4647;
  wire [2 : 0] b_expBotHalf__h4631,
	       b_expTopHalf__h4629,
	       repBound__h1290,
	       tb__h1288;
  wire [1 : 0] IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1016,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1051,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d106,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1086,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1121,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1156,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d141,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d176,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d211,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d246,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d281,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d316,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d351,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d386,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d421,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d456,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d491,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d526,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d561,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d596,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d631,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d666,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d701,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d72,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d736,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d771,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d806,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d841,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d876,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d911,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d946,
	       IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d981,
	       carry_out__h4452,
	       impliedTopBits__h4454,
	       len_correction__h4453,
	       x__h7005;
  wire IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1000,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1035,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1070,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1105,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1140,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d125,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d160,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d195,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d230,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d265,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d300,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d32,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d335,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d370,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d405,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d440,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d475,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d510,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d545,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d580,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d615,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d650,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d685,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d720,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d755,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d790,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d825,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d860,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d895,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d90,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d930,
       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d965;

  // value method wrap64_vectorBoundsDecompress
  assign wrap64_vectorBoundsDecompress =
	     { x__h2967[31:0],
	       x__h6979,
	       x__h7457[31:0],
	       x__h9110,
	       x__h9500[31:0],
	       x__h11153,
	       x__h11543[31:0],
	       x__h13196,
	       x__h13586[31:0],
	       x__h15239,
	       x__h15629[31:0],
	       x__h17282,
	       x__h17672[31:0],
	       x__h19325,
	       x__h19715[31:0],
	       x__h21368,
	       x__h21758[31:0],
	       x__h23411,
	       x__h23801[31:0],
	       x__h25454,
	       x__h25844[31:0],
	       x__h27497,
	       x__h27887[31:0],
	       x__h29540,
	       x__h29930[31:0],
	       x__h31583,
	       x__h31973[31:0],
	       x__h33626,
	       x__h34016[31:0],
	       x__h35669,
	       x__h36059[31:0],
	       x__h37712,
	       x__h38102[31:0],
	       x__h39755,
	       x__h40145[31:0],
	       x__h41798,
	       x__h42188[31:0],
	       x__h43841,
	       x__h44231[31:0],
	       x__h45884,
	       x__h46274[31:0],
	       x__h47927,
	       x__h48317[31:0],
	       x__h49970,
	       x__h50360[31:0],
	       x__h52013,
	       x__h52403[31:0],
	       x__h54056,
	       x__h54446[31:0],
	       x__h56099,
	       x__h56489[31:0],
	       x__h58142,
	       x__h58532[31:0],
	       x__h60185,
	       x__h60575[31:0],
	       x__h62228,
	       x__h62618[31:0],
	       x__h64271,
	       x__h64661[31:0],
	       x__h66314,
	       x__h66704[31:0],
	       x__h68357,
	       x__h68747[31:0],
	       x__h70400 } ;

  // remaining internal signals
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1016 =
	     top__h1914[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h60575[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1051 =
	     top__h1929[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h62618[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d106 =
	     top__h1524[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h7457[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1086 =
	     top__h1944[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h64661[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1121 =
	     top__h1959[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h66704[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1156 =
	     top__h1974[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h68747[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d141 =
	     top__h1539[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h9500[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d176 =
	     top__h1554[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h11543[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d211 =
	     top__h1569[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h13586[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d246 =
	     top__h1584[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h15629[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d281 =
	     top__h1599[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h17672[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d316 =
	     top__h1614[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h19715[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d351 =
	     top__h1629[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h21758[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d386 =
	     top__h1644[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h23801[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d421 =
	     top__h1659[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h25844[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d456 =
	     top__h1674[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h27887[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d491 =
	     top__h1689[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h29930[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d526 =
	     top__h1704[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h31973[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d561 =
	     top__h1719[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h34016[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d596 =
	     top__h1734[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h36059[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d631 =
	     top__h1749[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h38102[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d666 =
	     top__h1764[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h40145[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d701 =
	     top__h1779[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h42188[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d72 =
	     top__h1509[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h2967[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d736 =
	     top__h1794[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h44231[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d771 =
	     top__h1809[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h46274[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d806 =
	     top__h1824[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h48317[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d841 =
	     top__h1839[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h50360[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d876 =
	     top__h1854[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h52403[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d911 =
	     top__h1869[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h54446[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d946 =
	     top__h1884[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h56489[31] } ;
  assign IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d981 =
	     top__h1899[32:31] -
	     { 1'b0,
	       (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ==
		6'd24) ?
		 x__h7008[7] :
		 x__h58532[31] } ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1000 =
	     x__h61427[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1035 =
	     x__h63470[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1070 =
	     x__h65513[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1105 =
	     x__h67556[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1140 =
	     x__h69599[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d125 =
	     x__h10352[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 =
	     x__h7008[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d160 =
	     x__h12395[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d195 =
	     x__h14438[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       { b_expTopHalf__h4629, b_expBotHalf__h4631 } :
	       6'd0 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d230 =
	     x__h16481[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d265 =
	     x__h18524[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d300 =
	     x__h20567[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d32 =
	     x__h5438[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d335 =
	     x__h22610[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d370 =
	     x__h24653[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d405 =
	     x__h26696[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 =
	     IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 <
	     6'd25 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d440 =
	     x__h28739[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d475 =
	     x__h30782[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d50 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       { wrap64_vectorBoundsDecompress_cboundsRaw[13:11], 3'd0 } :
	       b_top__h4647 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d510 =
	     x__h32825[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d545 =
	     x__h34868[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d580 =
	     x__h36911[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 =
	     tb__h1288 < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d615 =
	     x__h38954[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d650 =
	     x__h40997[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d685 =
	     x__h43040[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d720 =
	     x__h45083[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d755 =
	     x__h47126[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d790 =
	     x__h49169[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d825 =
	     x__h51212[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d860 =
	     x__h53255[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d895 =
	     x__h55298[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d90 =
	     x__h8309[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d930 =
	     x__h57341[7:5] < repBound__h1290 ;
  assign IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d965 =
	     x__h59384[7:5] < repBound__h1290 ;
  assign addrUpperBits__h1504 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[1023:1000] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1519 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[991:968] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1534 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[959:936] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1549 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[927:904] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1564 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[895:872] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1579 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[863:840] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1594 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[831:808] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1609 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[799:776] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1624 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[767:744] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1639 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[735:712] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1654 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[703:680] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1669 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[671:648] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1684 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[639:616] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1699 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[607:584] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1714 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[575:552] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1729 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[543:520] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1744 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[511:488] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1759 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[479:456] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1774 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[447:424] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1789 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[415:392] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1804 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[383:360] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1819 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[351:328] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1834 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[319:296] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1849 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[287:264] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1864 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[255:232] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1879 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[223:200] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1894 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[191:168] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1909 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[159:136] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1924 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[127:104] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1939 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[95:72] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1954 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[63:40] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperBits__h1969 =
	     { 1'b0, wrap64_vectorBoundsDecompress_addrs[31:8] } &
	     allOnesExpShifted__h1301 ;
  assign addrUpperHi__h1505 =
	     addrUpperBits__h1504 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d32 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1520 =
	     addrUpperBits__h1519 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d90 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1535 =
	     addrUpperBits__h1534 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d125 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1550 =
	     addrUpperBits__h1549 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d160 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1565 =
	     addrUpperBits__h1564 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d195 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1580 =
	     addrUpperBits__h1579 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d230 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1595 =
	     addrUpperBits__h1594 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d265 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1610 =
	     addrUpperBits__h1609 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d300 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1625 =
	     addrUpperBits__h1624 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d335 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1640 =
	     addrUpperBits__h1639 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d370 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1655 =
	     addrUpperBits__h1654 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d405 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1670 =
	     addrUpperBits__h1669 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d440 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1685 =
	     addrUpperBits__h1684 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d475 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1700 =
	     addrUpperBits__h1699 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d510 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1715 =
	     addrUpperBits__h1714 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d545 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1730 =
	     addrUpperBits__h1729 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d580 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1745 =
	     addrUpperBits__h1744 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d615 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1760 =
	     addrUpperBits__h1759 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d650 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1775 =
	     addrUpperBits__h1774 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d685 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1790 =
	     addrUpperBits__h1789 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d720 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1805 =
	     addrUpperBits__h1804 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d755 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1820 =
	     addrUpperBits__h1819 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d790 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1835 =
	     addrUpperBits__h1834 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d825 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1850 =
	     addrUpperBits__h1849 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d860 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1865 =
	     addrUpperBits__h1864 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d895 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1880 =
	     addrUpperBits__h1879 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d930 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1895 =
	     addrUpperBits__h1894 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d965 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1910 =
	     addrUpperBits__h1909 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1000 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1925 =
	     addrUpperBits__h1924 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1035 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1940 =
	     addrUpperBits__h1939 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1070 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1955 =
	     addrUpperBits__h1954 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1105 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperHi__h1970 =
	     addrUpperBits__h1969 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1140 ?
		25'd0 :
		oneExpShifted__h1302) ;
  assign addrUpperLo__h1506 =
	     addrUpperBits__h1504 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d32 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1521 =
	     addrUpperBits__h1519 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d90 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1536 =
	     addrUpperBits__h1534 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d125 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1551 =
	     addrUpperBits__h1549 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d160 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1566 =
	     addrUpperBits__h1564 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d195 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1581 =
	     addrUpperBits__h1579 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d230 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1596 =
	     addrUpperBits__h1594 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d265 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1611 =
	     addrUpperBits__h1609 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d300 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1626 =
	     addrUpperBits__h1624 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d335 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1641 =
	     addrUpperBits__h1639 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d370 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1656 =
	     addrUpperBits__h1654 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d405 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1671 =
	     addrUpperBits__h1669 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d440 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1686 =
	     addrUpperBits__h1684 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d475 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1701 =
	     addrUpperBits__h1699 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d510 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1716 =
	     addrUpperBits__h1714 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d545 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1731 =
	     addrUpperBits__h1729 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d580 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1746 =
	     addrUpperBits__h1744 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d615 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1761 =
	     addrUpperBits__h1759 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d650 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1776 =
	     addrUpperBits__h1774 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d685 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1791 =
	     addrUpperBits__h1789 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d720 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1806 =
	     addrUpperBits__h1804 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d755 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1821 =
	     addrUpperBits__h1819 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d790 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1836 =
	     addrUpperBits__h1834 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d825 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1851 =
	     addrUpperBits__h1849 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d860 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1866 =
	     addrUpperBits__h1864 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d895 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1881 =
	     addrUpperBits__h1879 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d930 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1896 =
	     addrUpperBits__h1894 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d965 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1911 =
	     addrUpperBits__h1909 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1000 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1926 =
	     addrUpperBits__h1924 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1035 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1941 =
	     addrUpperBits__h1939 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1070 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1956 =
	     addrUpperBits__h1954 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1105 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign addrUpperLo__h1971 =
	     addrUpperBits__h1969 +
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d1140 ?
		allOnesExpShifted__h1301 :
		25'd0) ;
  assign allOnesExpShifted__h1301 =
	     25'd33554431 <<
	     IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ;
  assign b_base__h4648 =
	     { wrap64_vectorBoundsDecompress_cboundsRaw[7:2],
	       ~wrap64_vectorBoundsDecompress_cboundsRaw[1],
	       wrap64_vectorBoundsDecompress_cboundsRaw[0] } ;
  assign b_expBotHalf__h4631 =
	     { wrap64_vectorBoundsDecompress_cboundsRaw[2],
	       ~wrap64_vectorBoundsDecompress_cboundsRaw[1],
	       wrap64_vectorBoundsDecompress_cboundsRaw[0] } ;
  assign b_expTopHalf__h4629 =
	     { wrap64_vectorBoundsDecompress_cboundsRaw[10],
	       ~wrap64_vectorBoundsDecompress_cboundsRaw[9:8] } ;
  assign b_top__h4647 =
	     { wrap64_vectorBoundsDecompress_cboundsRaw[13:10],
	       ~wrap64_vectorBoundsDecompress_cboundsRaw[9:8] } ;
  assign baseBitsFull__h1297 =
	     { 25'd0, x__h7008 } <<
	     IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ;
  assign carry_out__h4452 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d50 <
	      x__h7008[5:0]) ?
	       2'b01 :
	       2'b0 ;
  assign impliedTopBits__h4454 = x__h7005 + len_correction__h4453 ;
  assign len_correction__h4453 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ? 2'b01 : 2'b0 ;
  assign oneExpShifted__h1302 =
	     25'd1 <<
	     IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ;
  assign repBound__h1290 = x__h7008[7:5] - 3'b001 ;
  assign result__h11443 = { ~top__h1539[32], top__h1539[31:0] } ;
  assign result__h13486 = { ~top__h1554[32], top__h1554[31:0] } ;
  assign result__h15529 = { ~top__h1569[32], top__h1569[31:0] } ;
  assign result__h17572 = { ~top__h1584[32], top__h1584[31:0] } ;
  assign result__h19615 = { ~top__h1599[32], top__h1599[31:0] } ;
  assign result__h21658 = { ~top__h1614[32], top__h1614[31:0] } ;
  assign result__h23701 = { ~top__h1629[32], top__h1629[31:0] } ;
  assign result__h25744 = { ~top__h1644[32], top__h1644[31:0] } ;
  assign result__h27787 = { ~top__h1659[32], top__h1659[31:0] } ;
  assign result__h29830 = { ~top__h1674[32], top__h1674[31:0] } ;
  assign result__h31873 = { ~top__h1689[32], top__h1689[31:0] } ;
  assign result__h33916 = { ~top__h1704[32], top__h1704[31:0] } ;
  assign result__h35959 = { ~top__h1719[32], top__h1719[31:0] } ;
  assign result__h38002 = { ~top__h1734[32], top__h1734[31:0] } ;
  assign result__h40045 = { ~top__h1749[32], top__h1749[31:0] } ;
  assign result__h42088 = { ~top__h1764[32], top__h1764[31:0] } ;
  assign result__h44131 = { ~top__h1779[32], top__h1779[31:0] } ;
  assign result__h46174 = { ~top__h1794[32], top__h1794[31:0] } ;
  assign result__h48217 = { ~top__h1809[32], top__h1809[31:0] } ;
  assign result__h50260 = { ~top__h1824[32], top__h1824[31:0] } ;
  assign result__h52303 = { ~top__h1839[32], top__h1839[31:0] } ;
  assign result__h54346 = { ~top__h1854[32], top__h1854[31:0] } ;
  assign result__h56389 = { ~top__h1869[32], top__h1869[31:0] } ;
  assign result__h58432 = { ~top__h1884[32], top__h1884[31:0] } ;
  assign result__h60475 = { ~top__h1899[32], top__h1899[31:0] } ;
  assign result__h62518 = { ~top__h1914[32], top__h1914[31:0] } ;
  assign result__h64561 = { ~top__h1929[32], top__h1929[31:0] } ;
  assign result__h66604 = { ~top__h1944[32], top__h1944[31:0] } ;
  assign result__h68647 = { ~top__h1959[32], top__h1959[31:0] } ;
  assign result__h70690 = { ~top__h1974[32], top__h1974[31:0] } ;
  assign result__h7357 = { ~top__h1509[32], top__h1509[31:0] } ;
  assign result__h9400 = { ~top__h1524[32], top__h1524[31:0] } ;
  assign tb__h1288 =
	     { impliedTopBits__h4454,
	       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d50[5] } ;
  assign topBitsFull__h1298 =
	     { 25'd0, topBits__h1295 } <<
	     IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d23 ;
  assign topBits__h1295 =
	     { impliedTopBits__h4454,
	       IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d50 } ;
  assign top__h1509 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1505 :
		 addrUpperLo__h1506,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1524 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1520 :
		 addrUpperLo__h1521,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1539 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1535 :
		 addrUpperLo__h1536,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1554 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1550 :
		 addrUpperLo__h1551,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1569 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1565 :
		 addrUpperLo__h1566,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1584 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1580 :
		 addrUpperLo__h1581,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1599 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1595 :
		 addrUpperLo__h1596,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1614 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1610 :
		 addrUpperLo__h1611,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1629 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1625 :
		 addrUpperLo__h1626,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1644 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1640 :
		 addrUpperLo__h1641,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1659 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1655 :
		 addrUpperLo__h1656,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1674 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1670 :
		 addrUpperLo__h1671,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1689 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1685 :
		 addrUpperLo__h1686,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1704 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1700 :
		 addrUpperLo__h1701,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1719 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1715 :
		 addrUpperLo__h1716,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1734 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1730 :
		 addrUpperLo__h1731,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1749 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1745 :
		 addrUpperLo__h1746,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1764 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1760 :
		 addrUpperLo__h1761,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1779 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1775 :
		 addrUpperLo__h1776,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1794 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1790 :
		 addrUpperLo__h1791,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1809 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1805 :
		 addrUpperLo__h1806,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1824 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1820 :
		 addrUpperLo__h1821,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1839 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1835 :
		 addrUpperLo__h1836,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1854 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1850 :
		 addrUpperLo__h1851,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1869 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1865 :
		 addrUpperLo__h1866,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1884 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1880 :
		 addrUpperLo__h1881,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1899 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1895 :
		 addrUpperLo__h1896,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1914 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1910 :
		 addrUpperLo__h1911,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1929 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1925 :
		 addrUpperLo__h1926,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1944 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1940 :
		 addrUpperLo__h1941,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1959 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1955 :
		 addrUpperLo__h1956,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign top__h1974 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d59 ?
		 addrUpperHi__h1970 :
		 addrUpperLo__h1971,
	       8'd0 } |
	     topBitsFull__h1298 ;
  assign x__h10352 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h11107[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[935:928] ;
  assign x__h11107 =
	     wrap64_vectorBoundsDecompress_addrs[959:928] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h11153 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d141 >
	      2'd1) ?
	       result__h11443 :
	       top__h1539 ;
  assign x__h11543 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1550 :
		 addrUpperLo__h1551,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h12395 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h13150[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[903:896] ;
  assign x__h13150 =
	     wrap64_vectorBoundsDecompress_addrs[927:896] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h13196 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d176 >
	      2'd1) ?
	       result__h13486 :
	       top__h1554 ;
  assign x__h13586 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1565 :
		 addrUpperLo__h1566,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h14438 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h15193[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[871:864] ;
  assign x__h15193 =
	     wrap64_vectorBoundsDecompress_addrs[895:864] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h15239 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d211 >
	      2'd1) ?
	       result__h15529 :
	       top__h1569 ;
  assign x__h15629 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1580 :
		 addrUpperLo__h1581,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h16481 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h17236[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[839:832] ;
  assign x__h17236 =
	     wrap64_vectorBoundsDecompress_addrs[863:832] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h17282 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d246 >
	      2'd1) ?
	       result__h17572 :
	       top__h1584 ;
  assign x__h17672 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1595 :
		 addrUpperLo__h1596,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h18524 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h19279[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[807:800] ;
  assign x__h19279 =
	     wrap64_vectorBoundsDecompress_addrs[831:800] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h19325 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d281 >
	      2'd1) ?
	       result__h19615 :
	       top__h1599 ;
  assign x__h19715 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1610 :
		 addrUpperLo__h1611,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h20567 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h21322[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[775:768] ;
  assign x__h21322 =
	     wrap64_vectorBoundsDecompress_addrs[799:768] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h21368 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d316 >
	      2'd1) ?
	       result__h21658 :
	       top__h1614 ;
  assign x__h21758 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1625 :
		 addrUpperLo__h1626,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h22610 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h23365[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[743:736] ;
  assign x__h23365 =
	     wrap64_vectorBoundsDecompress_addrs[767:736] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h23411 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d351 >
	      2'd1) ?
	       result__h23701 :
	       top__h1629 ;
  assign x__h23801 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1640 :
		 addrUpperLo__h1641,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h24653 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h25408[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[711:704] ;
  assign x__h25408 =
	     wrap64_vectorBoundsDecompress_addrs[735:704] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h25454 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d386 >
	      2'd1) ?
	       result__h25744 :
	       top__h1644 ;
  assign x__h25844 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1655 :
		 addrUpperLo__h1656,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h26696 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h27451[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[679:672] ;
  assign x__h27451 =
	     wrap64_vectorBoundsDecompress_addrs[703:672] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h27497 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d421 >
	      2'd1) ?
	       result__h27787 :
	       top__h1659 ;
  assign x__h27887 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1670 :
		 addrUpperLo__h1671,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h28739 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h29494[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[647:640] ;
  assign x__h29494 =
	     wrap64_vectorBoundsDecompress_addrs[671:640] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h29540 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d456 >
	      2'd1) ?
	       result__h29830 :
	       top__h1674 ;
  assign x__h2967 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1505 :
		 addrUpperLo__h1506,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h29930 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1685 :
		 addrUpperLo__h1686,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h30782 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h31537[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[615:608] ;
  assign x__h31537 =
	     wrap64_vectorBoundsDecompress_addrs[639:608] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h31583 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d491 >
	      2'd1) ?
	       result__h31873 :
	       top__h1689 ;
  assign x__h31973 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1700 :
		 addrUpperLo__h1701,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h32825 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h33580[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[583:576] ;
  assign x__h33580 =
	     wrap64_vectorBoundsDecompress_addrs[607:576] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h33626 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d526 >
	      2'd1) ?
	       result__h33916 :
	       top__h1704 ;
  assign x__h34016 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1715 :
		 addrUpperLo__h1716,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h34868 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h35623[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[551:544] ;
  assign x__h35623 =
	     wrap64_vectorBoundsDecompress_addrs[575:544] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h35669 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d561 >
	      2'd1) ?
	       result__h35959 :
	       top__h1719 ;
  assign x__h36059 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1730 :
		 addrUpperLo__h1731,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h36911 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h37666[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[519:512] ;
  assign x__h37666 =
	     wrap64_vectorBoundsDecompress_addrs[543:512] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h37712 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d596 >
	      2'd1) ?
	       result__h38002 :
	       top__h1734 ;
  assign x__h38102 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1745 :
		 addrUpperLo__h1746,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h38954 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h39709[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[487:480] ;
  assign x__h39709 =
	     wrap64_vectorBoundsDecompress_addrs[511:480] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h39755 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d631 >
	      2'd1) ?
	       result__h40045 :
	       top__h1749 ;
  assign x__h40145 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1760 :
		 addrUpperLo__h1761,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h40997 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h41752[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[455:448] ;
  assign x__h41752 =
	     wrap64_vectorBoundsDecompress_addrs[479:448] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h41798 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d666 >
	      2'd1) ?
	       result__h42088 :
	       top__h1764 ;
  assign x__h42188 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1775 :
		 addrUpperLo__h1776,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h43040 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h43795[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[423:416] ;
  assign x__h43795 =
	     wrap64_vectorBoundsDecompress_addrs[447:416] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h43841 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d701 >
	      2'd1) ?
	       result__h44131 :
	       top__h1779 ;
  assign x__h44231 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1790 :
		 addrUpperLo__h1791,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h45083 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h45838[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[391:384] ;
  assign x__h45838 =
	     wrap64_vectorBoundsDecompress_addrs[415:384] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h45884 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d736 >
	      2'd1) ?
	       result__h46174 :
	       top__h1794 ;
  assign x__h46274 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1805 :
		 addrUpperLo__h1806,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h47126 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h47881[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[359:352] ;
  assign x__h47881 =
	     wrap64_vectorBoundsDecompress_addrs[383:352] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h47927 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d771 >
	      2'd1) ?
	       result__h48217 :
	       top__h1809 ;
  assign x__h48317 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1820 :
		 addrUpperLo__h1821,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h49169 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h49924[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[327:320] ;
  assign x__h49924 =
	     wrap64_vectorBoundsDecompress_addrs[351:320] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h49970 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d806 >
	      2'd1) ?
	       result__h50260 :
	       top__h1824 ;
  assign x__h50360 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1835 :
		 addrUpperLo__h1836,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h51212 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h51967[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[295:288] ;
  assign x__h51967 =
	     wrap64_vectorBoundsDecompress_addrs[319:288] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h52013 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d841 >
	      2'd1) ?
	       result__h52303 :
	       top__h1839 ;
  assign x__h52403 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1850 :
		 addrUpperLo__h1851,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h53255 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h54010[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[263:256] ;
  assign x__h54010 =
	     wrap64_vectorBoundsDecompress_addrs[287:256] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h54056 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d876 >
	      2'd1) ?
	       result__h54346 :
	       top__h1854 ;
  assign x__h5438 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h6863[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[999:992] ;
  assign x__h54446 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1865 :
		 addrUpperLo__h1866,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h55298 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h56053[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[231:224] ;
  assign x__h56053 =
	     wrap64_vectorBoundsDecompress_addrs[255:224] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h56099 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d911 >
	      2'd1) ?
	       result__h56389 :
	       top__h1869 ;
  assign x__h56489 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1880 :
		 addrUpperLo__h1881,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h57341 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h58096[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[199:192] ;
  assign x__h58096 =
	     wrap64_vectorBoundsDecompress_addrs[223:192] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h58142 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d946 >
	      2'd1) ?
	       result__h58432 :
	       top__h1884 ;
  assign x__h58532 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1895 :
		 addrUpperLo__h1896,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h59384 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h60139[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[167:160] ;
  assign x__h60139 =
	     wrap64_vectorBoundsDecompress_addrs[191:160] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h60185 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d981 >
	      2'd1) ?
	       result__h60475 :
	       top__h1899 ;
  assign x__h60575 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1910 :
		 addrUpperLo__h1911,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h61427 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h62182[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[135:128] ;
  assign x__h62182 =
	     wrap64_vectorBoundsDecompress_addrs[159:128] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h62228 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1016 >
	      2'd1) ?
	       result__h62518 :
	       top__h1914 ;
  assign x__h62618 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1925 :
		 addrUpperLo__h1926,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h63470 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h64225[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[103:96] ;
  assign x__h64225 =
	     wrap64_vectorBoundsDecompress_addrs[127:96] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h64271 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1051 >
	      2'd1) ?
	       result__h64561 :
	       top__h1929 ;
  assign x__h64661 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1940 :
		 addrUpperLo__h1941,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h65513 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h66268[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[71:64] ;
  assign x__h66268 =
	     wrap64_vectorBoundsDecompress_addrs[95:64] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h66314 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1086 >
	      2'd1) ?
	       result__h66604 :
	       top__h1944 ;
  assign x__h66704 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1955 :
		 addrUpperLo__h1956,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h67556 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h68311[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[39:32] ;
  assign x__h68311 =
	     wrap64_vectorBoundsDecompress_addrs[63:32] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h68357 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1121 >
	      2'd1) ?
	       result__h68647 :
	       top__h1959 ;
  assign x__h6863 =
	     wrap64_vectorBoundsDecompress_addrs[1023:992] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h68747 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1970 :
		 addrUpperLo__h1971,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h69599 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h70354[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[7:0] ;
  assign x__h6979 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d72 >
	      2'd1) ?
	       result__h7357 :
	       top__h1509 ;
  assign x__h7005 = x__h7008[7:6] + carry_out__h4452 ;
  assign x__h7008 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       { wrap64_vectorBoundsDecompress_cboundsRaw[7:3], 3'd0 } :
	       b_base__h4648 ;
  assign x__h70354 =
	     wrap64_vectorBoundsDecompress_addrs[31:0] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h70400 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d1156 >
	      2'd1) ?
	       result__h70690 :
	       top__h1974 ;
  assign x__h7457 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1520 :
		 addrUpperLo__h1521,
	       8'd0 } |
	     baseBitsFull__h1297 ;
  assign x__h8309 =
	     (~wrap64_vectorBoundsDecompress_cboundsRaw[14]) ?
	       x__h9064[7:0] :
	       wrap64_vectorBoundsDecompress_addrs[967:960] ;
  assign x__h9064 =
	     wrap64_vectorBoundsDecompress_addrs[991:960] >>
	     { b_expTopHalf__h4629, b_expBotHalf__h4631 } ;
  assign x__h9110 =
	     (IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d44 &&
	      IF_IF_INV_wrap64_vectorBoundsDecompress_cbound_ETC___d106 >
	      2'd1) ?
	       result__h9400 :
	       top__h1524 ;
  assign x__h9500 =
	     { IF_INV_wrap64_vectorBoundsDecompress_cboundsRa_ETC___d13 ?
		 addrUpperHi__h1535 :
		 addrUpperLo__h1536,
	       8'd0 } |
	     baseBitsFull__h1297 ;
endmodule  // module_wrap64_vectorBoundsDecompress

