//
// Generated by Bluespec Compiler (build 6a8cedf)
//
// On Thu Oct  5 12:21:07 UTC 2023
//
//
// Ports:
// Name                         I/O  size props
// wrap64_setPermsCapMem          O    65
// wrap64_setPermsCapMem_cap      I    65
// wrap64_setPermsCapMem_perms    I    31
//
// Combinational paths from inputs to outputs:
//   (wrap64_setPermsCapMem_cap,
//    wrap64_setPermsCapMem_perms) -> wrap64_setPermsCapMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_setPermsCapMem(wrap64_setPermsCapMem_cap,
				    wrap64_setPermsCapMem_perms,
				    wrap64_setPermsCapMem);
  // value method wrap64_setPermsCapMem
  input  [64 : 0] wrap64_setPermsCapMem_cap;
  input  [30 : 0] wrap64_setPermsCapMem_perms;
  output [64 : 0] wrap64_setPermsCapMem;

  // signals for module outputs
  wire [64 : 0] wrap64_setPermsCapMem;

  // value method wrap64_setPermsCapMem
  assign wrap64_setPermsCapMem =
	     { wrap64_setPermsCapMem_cap[64],
	       wrap64_setPermsCapMem_perms[11:0],
	       wrap64_setPermsCapMem_cap[51:0] } ;
endmodule  // module_wrap64_setPermsCapMem

