//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Tue Aug 10 09:31:30 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_nullCap                 O    91 const
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_nullCap(wrap64_nullCap);
  // value method wrap64_nullCap
  output [90 : 0] wrap64_nullCap;

  // signals for module outputs
  wire [90 : 0] wrap64_nullCap;

  // value method wrap64_nullCap
  assign wrap64_nullCap = 91'h00000000000001F690003F0 ;
endmodule  // module_wrap64_nullCap

