//
// Generated by Bluespec Compiler (build 14ff62d)
//
// On Sat Sep 25 09:11:05 BST 2021
//
//
// Ports:
// Name                         I/O  size props
// wrap64_nullWithAddr            O    91
// wrap64_nullWithAddr_addr       I    32
//
// Combinational paths from inputs to outputs:
//   wrap64_nullWithAddr_addr -> wrap64_nullWithAddr
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_nullWithAddr(wrap64_nullWithAddr_addr,
				  wrap64_nullWithAddr);
  // value method wrap64_nullWithAddr
  input  [31 : 0] wrap64_nullWithAddr_addr;
  output [90 : 0] wrap64_nullWithAddr;

  // signals for module outputs
  wire [90 : 0] wrap64_nullWithAddr;

  // remaining internal signals
  wire [7 : 0] res_addrBits__h102;

  // value method wrap64_nullWithAddr
  assign wrap64_nullWithAddr =
	     { 1'd0,
	       wrap64_nullWithAddr_addr,
	       res_addrBits__h102,
	       50'h0001F690003F0 } ;

  // remaining internal signals
  assign res_addrBits__h102 = { 2'd0, wrap64_nullWithAddr_addr[31:26] } ;
endmodule  // module_wrap64_nullWithAddr

