//
// Generated by Bluespec Compiler, version 2022.01-37-gaf852df5 (build af852df5)
//
// On Thu Jun 20 12:37:29 BST 2024
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getOffset               O    32
// wrap64_getOffset_cap           I    91
//
// Combinational paths from inputs to outputs:
//   wrap64_getOffset_cap -> wrap64_getOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getOffset(wrap64_getOffset_cap,
			       wrap64_getOffset);
  // value method wrap64_getOffset
  input  [90 : 0] wrap64_getOffset_cap;
  output [31 : 0] wrap64_getOffset;

  // signals for module outputs
  wire [31 : 0] wrap64_getOffset;

  // remaining internal signals
  wire [31 : 0] addrLSB__h66, x__h198, x__h77, x__h79, y__h197;
  wire [9 : 0] base__h64, offset__h65;

  // value method wrap64_getOffset
  assign wrap64_getOffset = x__h77 | addrLSB__h66 ;

  // remaining internal signals
  assign addrLSB__h66 = wrap64_getOffset_cap[89:58] & y__h197 ;
  assign base__h64 =
	     { wrap64_getOffset_cap[1:0], wrap64_getOffset_cap[17:10] } ;
  assign offset__h65 = { 2'b0, wrap64_getOffset_cap[57:50] } - base__h64 ;
  assign x__h198 = 32'hFFFFFFFF << wrap64_getOffset_cap[31:26] ;
  assign x__h77 = x__h79 << wrap64_getOffset_cap[31:26] ;
  assign x__h79 = { {22{offset__h65[9]}}, offset__h65 } ;
  assign y__h197 = ~x__h198 ;
endmodule  // module_wrap64_getOffset

